force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Reseller Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reseller Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Reseller Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderController.cls
public with sharing class OrderController {
    @AuraEnabled
    public static Id createOrder(List<Map<String, Object>> orderItems) {
        List<Order_Item__c> newOrderItems = new List<Order_Item__c>();

        for (Map<String, Object> item : orderItems) {
            Order_Item__c newItem = new Order_Item__c();
            newItem.Product__c = (Id) item.get('Id');
            newItem.Price__c = Double.valueOf(item.get('Price'));
            newItem.Quantity__c = Double.valueOf(item.get('Quantity'));
            newItem.Order__c = 'a0309000004F05cAAC';
            newOrderItems.add(newItem);
        }
        System.debug(newOrderItems);
        insert newOrderItems;

        return 'a0309000004F05cAAC';
    }

}   